#!/usr/bin/env bash

prefix="vcw_module_hkvb_infometis__$1"
prefix="vcw_module_hkvb_infometis__$1"

executionplane --silent docker container prune --force

if [[ "vcw_module_hkvb_infometis__vcw_infometis_repos" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcw_module_hkvb_infometis__vcw_infometis_repos"
		result=$(docker volume ls | grep "vcw_module_hkvb_infometis__vcw_infometis_repos")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi
