FROM hkvb/bash.wrapper:5.0.18

RUN apk update && apk add docker && apk add git && apk add inotify-tools && apk add nano && apk add curl && rm -rf /var/cache/apk/*

LABEL co.vcweb.schema-version="1.0" \
      co.vcweb.label="hkvb/infometis.base - External Build" \
      co.vcweb.description="Base Infometis infometisimage." \
      co.vcweb.realm="hkvb" \
      co.vcweb.image="infometis" \
      co.vcweb.flavor="base" \
      co.vcweb.tag="1.0.0" \
      co.vcweb.maintainer="vcw@vcweb.co"
